name: ci
on:
  release:
    types: [published]
  push:
    tags:
    branches:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: verify format
        run: make clang-format-check
  unix:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
        build-type:
          - Debug
          - Release
        compiler:
          - cpp: g++-12
            c: gcc-12
        shared:
          - OFF
        include:
          - os: ubuntu-22.04
            build-type: Debug
            compiler:
              cpp: clang++-14
              c: clang-14
            shared: OFF
          - os: ubuntu-22.04
            build-type: Debug
            compiler:
              cpp: g++-12
              c: gcc-12
            shared: ON
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure CMake
        run: cmake -S . -B ./build -DCMAKE_BUILD_TYPE:STRING=${{matrix.build-type}} -DSIMPLE_CPP_BASE64_WARNINGS_AS_ERRORS:BOOL=ON -DSIMPLE_CPP_BASE64_FUZZ_TESTING:BOOL=${{ startsWith(matrix.compiler.cpp, 'clang') }} -DBUILD_SHARED_LIBS:BOOL=${{matrix.shared}}
        env:
          CC: ${{matrix.compiler.c}}
          CXX: ${{matrix.compiler.cpp}}
      - name: Build
        run: cmake --build ./build -- -j 2
      - name: Test and coverage
        working-directory: ./build
        run: ctest . --output-on-failure
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.build-type == 'Release' }}
        with:
          files: |
            build/simple-base64-*
  windows:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
        build-type:
          - Debug
          - Release
        shared:
          - OFF
        include:
          - os: windows-2022
            build-type: Debug
            shared: ON
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure CMake
        run: cmake -S . -B ./build -DCMAKE_BUILD_TYPE:STRING=${{matrix.build-type}} -DSIMPLE_CPP_BASE64_WARNINGS_AS_ERRORS:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=${{matrix.shared}}
      - name: Build
        run: cmake --build ./build --config ${{matrix.build-type}} -- /m
      - name: Test and coverage
        working-directory: ./build
        run: ctest . --output-on-failure -C ${{matrix.build-type}}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') && matrix.build-type == 'Release' }}
        with:
          files: |
            build/${{matrix.build-type}}/simple-base64-*