name: ci
on:
  pull_request:
  release:
    types: [published]
  push:
    tags:
    branches:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: verify format
        run: make clang-format-check
  test:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-11
          - windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -S . -B ./build
      - name: Build
        run: cmake --build ./build
      - name: Test and coverage
        working-directory: ./build
        run: ctest . --output-on-failure